site_name: Ark
nav:
  - Home: index.md
  - Getting Started:
      - Introduction: getting-started/01_introduction.md
      - Compile from Source: getting-started/02_compile_from_source.md
      - Regtest Demo: getting-started/03_regtest_demo.md
  - Protocol:  protocol/intro.md

plugins:
  - search
  - macros
extra:
  bitcoin:
    taproot_output_size: "43 vbytes"
  ark:
    # The number of blocks 
    vtxo_exit_delta: 60 # 10*6
    vtxo_exit_delta_description: 6 hours
    vtxo_expiry_delta: 11520
    vtxo_expire_delta_description: 28 days


