[package]
name = "ark-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
log.workspace = true
rand.workspace = true
bitcoin.workspace = true
env_logger.workspace = true
bitcoind = "0.36.0"
